//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myStudyJournal2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Tags { get; set; }
        public override string ToString()
        {
            return $"{this.Id}\n{this.Date}\n{this.Title}\n{this.Tags}\n{this.Body}\n";
        }

        public static Post parseString(string post)
        {
            string[] postArr = post.Split('\n');
            return new Post()
            {
                Id = Convert.ToInt16(postArr[0]),
                Date = DateTime.Parse(postArr[1]),
                Title = postArr[2],
                Tags = postArr[3],
                Body = postArr[4]
            };
        }
    }
}
